[package]
name = "store"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
diesel = {version = "2.2.0", features = ["postgres", "chrono"]}
uuid = {version="1.17.0", features = ["v4"]}
